services:
  hls-streaming-api:
    container_name: exam-hls-streaming-api
    image: ghcr.io/bob-park/exam-hls-streaming-api
    build:
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64